name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.1.0
  - pyarrow=2.0
  - numpy=1.23.5 # Added
  #- flask=2.2.2
  - pip:
      - wandb==0.13.3 # Added
